version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_inventory
    environment:
      POSTGRES_DB: inventory           # Set the default database
      POSTGRES_USER: admin             # Set the username
      POSTGRES_PASSWORD: admin         # Set the password
    ports:
      - "5432:5432"                    # Expose PostgreSQL on port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data

volumes:
  pgdata:
